# targil 1
# if __name__ == '__main__':
# try:
# a = 1 / 0
# except:
# print("Division by zero")
#
# targil 2:
# try :
#   x = 1
#
# finally :
#
#  print("finally")
# the answer is yes
#Targil 3:
#Yes, try can come with except & finally / finally
#Targil 4
#Except handles all types of exceptions
# Targil 5
# This type of exception handler is a "Bad Practice" because it will give partial information and can show
# Targil 7
# my_file = open("c:/test/readme.txt",'w')
# my_file.close()
# Targil8
# my_file = open("c:/test/readme.txt",'w')
# my_file.write("readme-nivtoledano is the king")
# my_file.close()
# Targil 9
# my_file = open("c:/test/readme.txt",'r')
# str = my_file.read()
# print(str)
# my_file.close()
# Targil 9
# my_file2 = open("c:/test/hebrew.txt",'w',encoding='utf-8')
# my_file2.write("ניב המלך")
# my_file2.close()
#
# my_file2 = open("c:/test/hebrew.txt",'r',encoding='utf-8')
# str = my_file2.read()
# print(str)
#Targil 10
